name: Manual workflow
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - run: ls
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: main.yml
        branch: main
        name: dist-without-markdown
        path: artifacts
      
    - run: ls
    - name: GitHub Pages
      env: 
        GH_PAT: ${{ secrets.REPO_PAT }}
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-github-pages@1510b11c0c2f843eafb8ff41b3da8c467c8d4a9f
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        build_dir: artifacts/BlogPostViewer/dist/BlogPostViewer/
        repo: amoenus/amoenus.github.io
        
